---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 23.1.0
      valuesFiles:
        - traefik-values.yaml
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 12h
  # values:
  #   controller:
  #     service:
  #       enabled: true
  #       type: LoadBalancer
  #   annotations: {}
  #   labels: {}
  #   spec:
  #   loadBalancerIP: 192.168.1.251 # this should be an IP in the MetalLB range
  #   loadBalancerSourceRanges: []
  #   externalIPs: []

  #   providers:
  #     kubernetesCRD:
  #       enabled: true
  #       ingressClass: traefik-internal
  #       allowExternalNameServices: true
  #     kubernetesIngress:
  #       enabled: true
  #       allowExternalNameServices: true
  #       publishedService:
  #         enabled: false

  #   rbac:
  #     enabled: true

  #   ingressRoute:
  #     dashboard:
  #       enabled: false

  #   ports:
  #     web:
  #       redirectTo: websecure
  #     websecure:
  #       tls:
  #         enabled: true

  #   globalArguments:
  #     - "--global.sendanonymoususage=false"
  #     - "--global.checknewversion=false"

  #   additionalArguments:
  #     - "--serversTransport.insecureSkipVerify=true"
  #     - "--log.level=DEBUG"
